package hikversion;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import java.util.Base64;

/**
 * @author:jinyandong
 * @description:测试生成Bmp文件
 * @Date:2023/11/13
 */
public class TestBmpCopySansi {
    public static void main(String args[]) throws Exception {
        // 设备端返回的Bse64加密的字符串信息
        String str = "Qk02CAAAAAAAADYEAAAoAAAAIAAAACAAAAABAAgAAAAAAAAEAADEDgAAxA4AAAAAAAAAAAAAAAAAAEAAAACAAAAA/wAAAAAgAABAIAAAgCAAAP8gAAAAQAAAQEAAAIBAAAD/QAAAAGAAAEBgAACAYAAA/2AAAACAAABAgAAAgIAAAP+AAAAAoAAAQKAAAICgAAD/oAAAAMAAAEDAAACAwAAA/8AAAAD/AABA/wAAgP8AAP//AAAAACAAQAAgAIAAIAD/ACAAACAgAEAgIACAICAA/yAgAABAIABAQCAAgEAgAP9AIAAAYCAAQGAgAIBgIAD/YCAAAIAgAECAIACAgCAA/4AgAACgIABAoCAAgKAgAP+gIAAAwCAAQMAgAIDAIAD/wCAAAP8gAED/IACA/yAA//8gAAAAQABAAEAAgABAAP8AQAAAIEAAQCBAAIAgQAD/IEAAAEBAAEBAQACAQEAA/0BAAABgQABAYEAAgGBAAP9gQAAAgEAAQIBAAICAQAD/gEAAAKBAAECgQACAoEAA/6BAAADAQABAwEAAgMBAAP/AQAAA/0AAQP9AAID/QAD//0AAAABgAEAAYACAAGAA/wBgAAAgYABAIGAAgCBgAP8gYAAAQGAAQEBgAIBAYAD/QGAAAGBgAEBgYACAYGAA/2BgAACAYABAgGAAgIBgAP+AYAAAoGAAQKBgAICgYAD/oGAAAMBgAEDAYACAwGAA/8BgAAD/YABA/2AAgP9gAP//YAAAAIAAQACAAIAAgAD/AIAAACCAAEAggACAIIAA/yCAAABAgABAQIAAgECAAP9AgAAAYIAAQGCAAIBggAD/YIAAAICAAECAgACAgIAA/4CAAACggABAoIAAgKCAAP+ggAAAwIAAQMCAAIDAgAD/wIAAAP+AAED/gACA/4AA//+AAAAAoABAAKAAgACgAP8AoAAAIKAAQCCgAIAgoAD/IKAAAECgAEBAoACAQKAA/0CgAABgoABAYKAAgGCgAP9goAAAgKAAQICgAICAoAD/gKAAAKCgAECgoACAoKAA/6CgAADAoABAwKAAgMCgAP/AoAAA/6AAQP+gAID/oAD//6AAAADAAEAAwACAAMAA/wDAAAAgwABAIMAAgCDAAP8gwAAAQMAAQEDAAIBAwAD/QMAAAGDAAEBgwACAYMAA/2DAAACAwABAgMAAgIDAAP+AwAAAoMAAQKDAAICgwAD/oMAAAMDAAEDAwACAwMAA/8DAAAD/wABA/8AAgP/AAP//wAAAAP8AQAD/AIAA/wD/AP8AACD/AEAg/wCAIP8A/yD/AABA/wBAQP8AgED/AP9A/wAAYP8AQGD/AIBg/wD/YP8AAID/AECA/wCAgP8A/4D/AACg/wBAoP8AgKD/AP+g/wAAwP8AQMD/AIDA/wD/wP8AAP//AED//wCA//8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ADg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ADg4AAA/Pz8AAAAAAAA/PwAAAAAAPz8/Pz8/PwA4OAAAODgAAAA/PwAAAAAAAD8/AAA/Pz8/Pz8/Pz8AADg4AAAAODgAAD8/AAAAAAA/PwAAAAA/AAA/AD8/PwA4OAAAAAA4OAAAPz8AAAAAAD8/AAAAAD8AAD8APz8AADg4AAAAAAA4OAAAPz8AAAA/Pz8AAAA/Pz8/Pz8/AAA4OAAAAAAAADg4AAAAPz8AAD8/AAA/Pz8APwA/Pz8AADg4AAAAAAAAADg4AAA/Pz8APz8APz8AAAAAAD8/AAA4OAAAAAAAAAAAODgAAD8/Pz8/PwA/Pz8AAAAAAAAAADg4AAAAAAAAAAAAODgAAD8/Pz8/Pz8APwAAAAAAAAA4OAAAAAAAAAAAAAA4OAAAAD8/Pz8AAAA/AAAAAAAAADg4AAAAAAAAAAAAAAA4OD8APz8/Pz8APz8AAAAAAAA4OAAAAAAAAAAAAAAAADg4Pz8APz8/Pz8/PwAAAAAAADg4AAAAAAAAAAAAAAAAADg4Pz8/Pz8/Pz8AAAAAAAA4OAAAAAAAAAAAAAAAAAAAODg/Pz8/Pz8/PwAAAAAAADg4AAAAAAAAAAAAAAAAAAAAODgAAAAAAAAAAAAAAAA4OAAAAAAAAAAAAAAAAAAAAAA4OAAAAD8/AAAAAAAAADg4AAAAAAAAAAAAAAAAAAAAAAA4OAA/Pz8/AAAAAAA4OAAAAAAAAAAAAAAAAAAAAAAAADg4AD8/Pz8AAAAAADg4AAAAAAAAAAAAAAAAAAAAAAAAADg4AD8/AAAAAAA4OAAAAAAAAAAAAAAAAAAAAAAAAAAAODgAAAAAAAAAADg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAODgAAAAAAAA4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4OAAAAAAAADg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4OAAAAAA4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg4AAAAADg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg4AAA4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODgAADg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODg4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4ODg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4OAAAAAAAAAAAAAAAAAAAAA=";
        uploadFileToLocal(str);
    }

    /**
     * 根据设备端返回的数据转换成的字符串生成bmp文件
     *
     * @param str：设备端返回的base64加密的字节数组
     * @throws Exception
     */
    public static void uploadFileToLocal(String str) throws Exception {
        byte[] decode = Base64.getDecoder().decode(str);
        InputStream inputStream = new ByteArrayInputStream(decode);
        try {
            BufferedImage image = ImageIO.read(inputStream);
            // 文件生成路径
            File output = new File("D:\\sansib001.bmp");
            if (output.exists()) {
                output.delete();
            }
            ImageIO.write(image, "bmp", output);
        } catch (Exception e) {
            System.out.println("error");
        } finally {
            inputStream.close();
        }
    }

}
